export const EMAIL_CHANGED = 'EMAIL_CHANGED'
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'
export const BEGIN_LOGIN = 'BEGIN_LOGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

/*
  EMAIL_CHANGED,
  PASSWORD_CHANGED,
  BEGIN_LOADING,
  FINISHED_LOADING,
  ERROR_OCCURED,
  LOGIN_USER_SUCCESS,
*/
