export const EMAIL_CHANGED = 'EMAIL_CHANGED'
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'
export const BEGIN_LOADING = 'BEGIN_LOADING'
export const FINISHED_LOADING = 'FINISHED_LOADING'
export const ERROR_OCCURED = 'ERROR_OCCURED'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

/*
  EMAIL_CHANGED,
  PASSWORD_CHANGED,
  BEGIN_LOADING,
  FINISHED_LOADING,
  ERROR_OCCURED,
  USER_UPDATED,
*/
